config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :topics do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all.order('updated_at' + ' ' + 'desc')
    @topic = Topic.new
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topics = Topic.all.order('updated_at' + ' ' + 'desc')
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "トピックを作成しました！"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render 'index'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(topics_params)
    if @topic.save
      redirect_to topics_path, notice: "トピックを更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました！"
  end

  private
    def topics_params
      params.require(:topic).permit(:title, :content, :image, :image_cache, :remove_image)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <%= f.error_messages! %>

  <br>
  <p class="left"><%= link_to profile_img(current_user), current_user %></p>

  <%= f.text_field :content, class: 'form-control', placeholder: '今なにしてる？' %>

  <% unless @topic.image.url.blank? %>
    <%= f.label :現在の画像 %>
    <%= image_tag @topic.image.url %>
  <% end %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>

  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>トピックを編集する</h2>
    <%= render 'form' %>
    <%= link_to "トピック一覧画面にもどる", topics_path %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>トピック一覧</h1>
    <%= render 'form' %>
    <% @topics.each do |topic| %>
      <div class="row">
        <%= link_to profile_img(topic.user), topic.user %>
        <strong><%= link_to topic.user.name, topic.user %></strong>
        <p>作成日時：<%= topic.created_at.strftime("%Y/%m/%d %R") %></p>
        <p>投稿内容：<%= topic.content %></p>
        <div class="field">
          <% if topic.image? %>
            <p>画像:<%= image_tag topic.image.url %></p>
          <% end %>
        </div>
        <%= link_to "コメントする", topic_path(topic), class: 'btn btn-primary' %>
        <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
        <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>トピックを作成する</h2>
    <%= render 'form' %>
    <%= link_to "トピック一覧画面にもどる", topics_path %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="left"><strong>投稿内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <div class="left">
        <% if @topic.image? %>
          <p><%= image_tag @topic.image.url %></p>
        <% end %>
      </div>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%Y/%m/%d %R") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', :back %>
  </div>
</div>